#!/usr/bin/env bash

main () {
  local delay=2
  local should_delay_test=false
  local args=("$@")

  for ((i=0; i<"${#args[@]}"; i++)); do
    local arg="${args[i]}"
    case $arg in
      --delay=*|-D=*)
        should_delay_test=true
        delay="${arg#*=}"
        unset 'args[i]'
        ;;
      --delay|-D)
        should_delay_test=true
        unset 'args[i]'
        if [[ -n ${args[i+1]} && ${args[i+1]} =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
          delay="${args[i+1]}"
          unset 'args[i+1]'
        fi
        ;;
    esac
  done

  if [[ $should_delay_test == true ]]; then
    sleep "$delay"
  fi

  exec hs ./spacehammer/lib/testing/test.lua "$(pwd)" "${args[@]}"
}

main "$@"
